/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import java.awt.PopupMenu;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.SinhVien;

/**
 *
 * @author Admin
 */
public class View extends javax.swing.JFrame {

    public DefaultTableModel tableModel;
    List<SinhVien> sinhViens;
    public View() {
        initComponents();
        tableModel = (DefaultTableModel) jTable_data.getModel();
         sinhViens=new ArrayList<>();
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jFrame1 = new javax.swing.JFrame();
        jFrame_update = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jFrame3 = new javax.swing.JFrame();
        jFrame4 = new javax.swing.JFrame();
        jPanel_nhapThongTin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_maSo = new javax.swing.JTextField();
        jTextField_ten = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_ngaySinh = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_diaChi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_diemDauVao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton_them = new javax.swing.JButton();
        jButton_reset = new javax.swing.JButton();
        jButton_hienThi = new javax.swing.JButton();
        jButton_timKiem = new javax.swing.JButton();
        jButton_xoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_data = new javax.swing.JTable();

        jButton2.setText("jButton2");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jFrame_update.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jFrame_updateLayout = new javax.swing.GroupLayout(jFrame_update.getContentPane());
        jFrame_update.getContentPane().setLayout(jFrame_updateLayout);
        jFrame_updateLayout.setHorizontalGroup(
            jFrame_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame_updateLayout.setVerticalGroup(
            jFrame_updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
        jFrame4.getContentPane().setLayout(jFrame4Layout);
        jFrame4Layout.setHorizontalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame4Layout.setVerticalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nhap ma so:");

        jLabel2.setText("Nhap ten:");

        jLabel3.setText("Nhap ngay sinh:");

        jLabel4.setText("Nhap dia chi:");

        jLabel5.setText("Diem dau vao");

        jButton_them.setText("Them");
        jButton_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_themActionPerformed(evt);
            }
        });

        jButton_reset.setText("Reset");
        jButton_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_resetActionPerformed(evt);
            }
        });

        jButton_hienThi.setText("Hien Thi");
        jButton_hienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_hienThiActionPerformed(evt);
            }
        });

        jButton_timKiem.setText("Tim Kiem");
        jButton_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_timKiemActionPerformed(evt);
            }
        });

        jButton_xoa.setText("Delete");
        jButton_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_xoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_nhapThongTinLayout = new javax.swing.GroupLayout(jPanel_nhapThongTin);
        jPanel_nhapThongTin.setLayout(jPanel_nhapThongTinLayout);
        jPanel_nhapThongTinLayout.setHorizontalGroup(
            jPanel_nhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_nhapThongTinLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel_nhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_nhapThongTinLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_nhapThongTinLayout.createSequentialGroup()
                        .addComponent(jButton_them)
                        .addGap(27, 27, 27)))
                .addGroup(jPanel_nhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_diemDauVao, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_nhapThongTinLayout.createSequentialGroup()
                        .addComponent(jButton_reset)
                        .addGap(36, 36, 36)
                        .addComponent(jButton_hienThi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_timKiem)
                        .addGap(47, 47, 47)
                        .addComponent(jButton_xoa)
                        .addGap(16, 16, 16))))
            .addGroup(jPanel_nhapThongTinLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_nhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel_nhapThongTinLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_ten, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_nhapThongTinLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_maSo))
                    .addGroup(jPanel_nhapThongTinLayout.createSequentialGroup()
                        .addGroup(jPanel_nhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_nhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_nhapThongTinLayout.setVerticalGroup(
            jPanel_nhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_nhapThongTinLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel_nhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_maSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_nhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_nhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_nhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_nhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_diemDauVao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel_nhapThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_them)
                    .addComponent(jButton_reset)
                    .addComponent(jButton_hienThi)
                    .addComponent(jButton_timKiem)
                    .addComponent(jButton_xoa)))
        );

        jTable_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma so", "Ten", "Ngay sinh", "Dia Chi", "Diem dau vao"
            }
        ));
        jScrollPane1.setViewportView(jTable_data);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel_nhapThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_nhapThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_themActionPerformed
        if(jTextField_ten.getText().isEmpty()||jTextField_ngaySinh.getText().isEmpty()||
                jTextField_maSo.getText().isEmpty()||jTextField_diemDauVao.getText().isEmpty()||jTextField_diaChi.getText().isEmpty()
                ){
            JOptionPane.showMessageDialog(rootPane, "Khong duoc de trong thong tin");
            return;
        }
        SinhVien t=new SinhVien();
        t.setMaSo(jTextField_maSo.getText());
        t.setTen(jTextField_ten.getText());
        t.setNgaySinh(jTextField_ngaySinh.getText());
        t.setDiaChi(jTextField_diaChi.getText());
        t.setDiemDauVao(Float.valueOf(jTextField_diemDauVao.getText()));
        int check=0;
        for(int i=0;i<sinhViens.size();i++){
           if(jTextField_maSo.getText().equals(sinhViens.get(i).getMaSo())){
             check=1;
             JOptionPane.showMessageDialog(rootPane, "Ma so da ton tai nhap ma so khac");
            return;
           }
        }
        if(check==0){
           tableModel.addRow(new Object[]{t.getMaSo(),t.getTen(),t.getNgaySinh(),t.getDiaChi(),t.getDiemDauVao()+""});
        sinhViens.add(t);
        }
        
       // tableModel.addRow(new Object[]{"eqeq","qeqe","qeqe","qeqeq","qeqe"});
    }//GEN-LAST:event_jButton_themActionPerformed

    private void jButton_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_resetActionPerformed
         jTextField_diaChi.setText("");
         jTextField_diemDauVao.setText("");
          jTextField_maSo.setText("");
           jTextField_ngaySinh.setText("");
            jTextField_ten.setText("");
            tableModel.setRowCount(0);
   
    }//GEN-LAST:event_jButton_resetActionPerformed

    private void jButton_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_xoaActionPerformed
        int chon= jTable_data.getSelectedRow();
        if(chon==-1){
          JOptionPane.showMessageDialog(rootPane, "Hay chon dong can xoa");
            return;
        }
        else{
          String id=(String) jTable_data.getValueAt(chon, 0);
          for(int i=0;i<sinhViens.size();i++){
             if(id.equals(sinhViens.get(i).getMaSo())){
               sinhViens.remove(i);
               break;
             }
          }
          tableModel.removeRow(chon);
         
        }
    }//GEN-LAST:event_jButton_xoaActionPerformed

    private void jButton_hienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_hienThiActionPerformed
        
        for(int i=0;i<sinhViens.size();i++){
         tableModel.addRow(new Object[]{sinhViens.get(i).getMaSo(),sinhViens.get(i).getTen(),sinhViens.get(i).getNgaySinh(),sinhViens.get(i).getDiaChi(),sinhViens.get(i).getDiemDauVao()+""});
       }
       
    }//GEN-LAST:event_jButton_hienThiActionPerformed

    private void jButton_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_timKiemActionPerformed
        
        String t= JOptionPane.showInputDialog(rootPane,"Nhap ma sinh vien can tim kiem");
        
         if(t.equals("")){
           JOptionPane.showMessageDialog(rootPane, "Khong duoc de trong");
           return;
         }
           SinhVien s=new SinhVien();
           int check=0;
           for(int i=0;i<sinhViens.size();i++){
             if(t.equals(sinhViens.get(i).getMaSo())){
                   tableModel.setRowCount(0);
                   tableModel.addRow(new Object[]{sinhViens.get(i).getMaSo(),sinhViens.get(i).getTen(),sinhViens.get(i).getNgaySinh(),sinhViens.get(i).getDiaChi(),sinhViens.get(i).getDiemDauVao()+""});
                   check=1;
                break;
             }
             check=3;
           }
          if(check==0){
              JOptionPane.showMessageDialog(rootPane, "Khong tim thay trong he thong");
           return;
          }
          if(check==3){
             JOptionPane.showMessageDialog(rootPane, "Khong tim thay trong he thong");
          }
           
         
    }//GEN-LAST:event_jButton_timKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_hienThi;
    private javax.swing.JButton jButton_reset;
    private javax.swing.JButton jButton_them;
    private javax.swing.JButton jButton_timKiem;
    private javax.swing.JButton jButton_xoa;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JFrame jFrame_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel_nhapThongTin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_data;
    private javax.swing.JTextField jTextField_diaChi;
    private javax.swing.JTextField jTextField_diemDauVao;
    private javax.swing.JTextField jTextField_maSo;
    private javax.swing.JTextField jTextField_ngaySinh;
    private javax.swing.JTextField jTextField_ten;
    // End of variables declaration//GEN-END:variables
}

